const DEFAULT_MAX_TOKENS = 4096
const DEFAULT_CONTEXT_LENGTH = 32_768
const DEFAULT_PRUNING_LENGTH = 128000
export var NEXT_EDIT_MODELS
;(function (NEXT_EDIT_MODELS) {
	NEXT_EDIT_MODELS["MERCURY_CODER"] = "mercury-coder"
	NEXT_EDIT_MODELS["INSTINCT"] = "instinct"
})(NEXT_EDIT_MODELS || (NEXT_EDIT_MODELS = {}))
export { DEFAULT_CONTEXT_LENGTH, DEFAULT_MAX_TOKENS, DEFAULT_PRUNING_LENGTH }
//# sourceMappingURL=constants.js.map
